name: gluon_vision_docs
dependencies:
- python
- sphinx>=1.5.5
- scipy
- numpy
- matplotlib
- sphinx_rtd_theme
- pip:
  - git+https://github.com/mli/mx-theme.git@0.3
  - sphinx-gallery
  - mxnet-cu92mkl==1.5.0b20190115
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
  - tqdm
  - requests
  - Pillow
  - opencv-python
